import "./Primi.d";

export enum primi_tipi {
  spaghetti_aglioOlio,
  spaghetti_carbonara,
  spaghetti_amatriciana,
  spaghetti_pannaEsalsiccia,
  spaghetti_ricottaEsalsiccia,
  spaghetti_ai_frutti_di_mare,
  spaghetti_con_salsa,
  spaghetti_con_salsa_rosa,
  spaghetti_ragu,
  spaghetti_al_pesto,
  spaghetti_al_burro,
  spaghetti_al_tonno_mozzarella,
  spaghetti_alla_salsiccia_e_cime_di_rapa,
  orecchiette_alla_salsiccia_e_cime_di_rapa,
  tagliatelle_al_salmone,
  ditalini_al_burro,
  brodo_pastina,
  brodo_tortellini,
  brodo_nudel,
  brodo_nudel_uovo,
  brodo_nudel_uovo_pollo,
  brodo_nudel_uovo_manzo,
  risotto_formaggio,
  risotto_zafferano,
  lasagne_ragu,
  acqua_cotta,
  minestra_patate_pancetta,
  pizza_ai_quattro_formaggi,
  pizza_wurstel_patatine,
  pizza_margherita,
  pizza_cotto_funghi,
  pizza_cipolla_tonno,
}
